name: stock_scan_pro
description: Flutter app for managing serial numbers with Odoo 15 integration
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Local Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Secure Storage
  flutter_secure_storage: ^9.0.0
  
  # Barcode Scanning
  barcode_scan2: ^4.3.3
  permission_handler: ^11.0.1
  
  # UI & Navigation
  go_router: ^12.1.1
  flutter_svg: ^2.0.9
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.1.0
  connectivity_plus: ^5.0.1
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
